import express from 'express';
import cors from 'cors';
import pg from 'pg';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { migrateFirebase } from './migration-core.mjs';
const { Pool } = pg;
const app = express();
app.disable('x-powered-by');
const corsOrigins = (process.env.CORS_ORIGIN || 'https://liderancaindigofabio-lab.github.io').split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({ origin(origin, cb) { if (!origin || corsOrigins.includes(origin)) return cb(null, true); return cb(new Error('cors_denied')); }, methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowedHeaders:['Content-Type','Authorization','Idempotency-Key','X-Migration-Token'] }));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');next();});
app.use(express.json({ limit: '256kb' }));
const databaseUrl = process.env.DATABASE_URL;
const pool = new Pool({ connectionString: databaseUrl, ssl: databaseUrl ? { rejectUnauthorized:false } : false, max:5, connectionTimeoutMillis:3000, idleTimeoutMillis:10000 });
pool.on('error', e => console.error('[db]', e.message));
const secret = process.env.SESSION_SECRET || process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');
const schema = [
`CREATE TABLE IF NOT EXISTS restaurants(id text PRIMARY KEY,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),email text NOT NULL UNIQUE,name text NOT NULL,role text NOT NULL DEFAULT 'owner',password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),last_access_at timestamptz)`,
`CREATE TABLE IF NOT EXISTS products(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),category text NOT NULL DEFAULT 'Geral',name text NOT NULL,description text,price numeric(12,2) NOT NULL DEFAULT 0,cost numeric(12,2) NOT NULL DEFAULT 0,emoji text,image_url text,active boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS orders(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL DEFAULT 'pending',channel text,customer jsonb NOT NULL DEFAULT '{}',items jsonb NOT NULL DEFAULT '[]',subtotal numeric(12,2) NOT NULL DEFAULT 0,delivery_fee numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL DEFAULT 0,payment jsonb NOT NULL DEFAULT '{}',courier_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS order_events(id bigserial PRIMARY KEY,order_id text NOT NULL REFERENCES orders(id),status text NOT NULL,actor_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS inventory(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,category text,quantity numeric(12,3) NOT NULL DEFAULT 0,min_quantity numeric(12,3) NOT NULL DEFAULT 0,unit text NOT NULL DEFAULT 'un',updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS expenses(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),description text NOT NULL,category text,amount numeric(12,2) NOT NULL CHECK(amount>0),due_date date NOT NULL,paid boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS reservations(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),customer jsonb NOT NULL DEFAULT '{}',table_no text,starts_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'booked',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS cash_registers(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL,opened_at timestamptz,closed_at timestamptz,counted numeric(12,2),expected numeric(12,2))`,
`CREATE TABLE IF NOT EXISTS cash_movements(id text PRIMARY KEY,register_id text NOT NULL REFERENCES cash_registers(id),type text NOT NULL,amount numeric(12,2) NOT NULL CHECK(amount>0),description text,actor_id text,created_at timestamptz NOT NULL DEFAULT now())`,`CREATE TABLE IF NOT EXISTS migration_state(key text PRIMARY KEY,completed_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS restaurant_config(restaurant_id text PRIMARY KEY REFERENCES restaurants(id),data jsonb NOT NULL DEFAULT '{}',updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS motoboys(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,phone text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS courier_locations(id bigserial PRIMARY KEY,motoboy_id text NOT NULL REFERENCES motoboys(id),restaurant_id text NOT NULL REFERENCES restaurants(id),lat numeric(10,7) NOT NULL,lng numeric(10,7) NOT NULL,accuracy numeric(10,2),created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS customers(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,phone text,email text,address jsonb NOT NULL DEFAULT '{}',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(restaurant_id,phone))`,
`CREATE TABLE IF NOT EXISTS order_idempotency(restaurant_id text NOT NULL,key text NOT NULL,order_id text NOT NULL REFERENCES orders(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(restaurant_id,key))`,
`CREATE TABLE IF NOT EXISTS audit_log(id bigserial PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),actor_id text,action text NOT NULL,entity text,entity_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`];
let schemaReady = false, schemaPromise;
const id = () => crypto.randomUUID();
const json = v => v === undefined ? {} : v;
function hashPassword(password){ const salt=crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`; }
function checkPassword(password, stored){ try { if(typeof stored==='string' && stored.startsWith('$2')) return bcrypt.compareSync(password,stored); const [salt,key]=stored.split(':'); return crypto.timingSafeEqual(crypto.scryptSync(password,salt,64),Buffer.from(key,'hex')); } catch { return false; } }
function token(payload){ const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url'); return `${body}.${crypto.createHmac('sha256',secret).update(body).digest('base64url')}`; }
function readToken(raw){ try { const [body,sig]=raw.split('.'); const good=crypto.createHmac('sha256',secret).update(body).digest('base64url'); if(!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good))) return null; const p=JSON.parse(Buffer.from(body,'base64url')); return p.exp>Date.now()?p:null; } catch { return null; } }
async function ensureSchema(){ if(schemaReady) return; if(!schemaPromise) schemaPromise=(async()=>{ if(!databaseUrl) throw new Error('DATABASE_URL missing'); for(const statement of schema) await pool.query(statement); schemaReady=true; })().catch(e=>{schemaPromise=null; throw e}); return schemaPromise; }
async function q(text, params=[]){ await ensureSchema(); return pool.query({text,values:params}); }
async function auth(req,res,next){ const p=readToken((req.headers.authorization||'').replace(/^Bearer\s+/i,'')); if(!p?.uid||!p?.rid) return res.status(401).json({error:'unauthorized'}); try { const r=await q('SELECT id,restaurant_id,role FROM users WHERE id=$1 AND restaurant_id=$2 AND active=true',[p.uid,p.rid]); if(!r.rowCount) return res.status(401).json({error:'unauthorized'}); req.user={...p,uid:r.rows[0].id,rid:r.rows[0].restaurant_id,role:r.rows[0].role}; next(); } catch { res.status(503).json({error:'database_unavailable'}); } }
function bodyFields(body, allowed){ return allowed.map(k=>body[k]); }
const roles = (...allowed) => (req,res,next) => allowed.includes(req.user?.role) ? next() : res.status(403).json({error:'forbidden'});
const staff = roles('owner','admin','manager','cashier','staff');
const manager = roles('owner','admin','manager');
const courierOrStaff = roles('owner','admin','manager','cashier','staff','courier');
const cleanText=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v,min=0)=>Number.isFinite(Number(v))&&Number(v)>=min?Number(v):null;
async function audit(req,action,entity,entityId,metadata={}){ try{await q('INSERT INTO audit_log(restaurant_id,actor_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[req.user.rid,req.user.uid,action,entity,entityId,metadata]);}catch(e){console.error('[audit]',e.message)} }

const listRoutes = {
 products:['products',['category','name','description','price','cost','emoji','image_url','active']], inventory:['inventory',['name','category','quantity','min_quantity','unit']], expenses:['expenses',['description','category','amount','due_date','paid']], reservations:['reservations',['customer','table_no','starts_at','status']]
};
app.get('/health', async (_,res)=>{ try { await ensureSchema(); res.json({ok:true,service:'nonna-pizzaria-api',database:'connected'}); } catch(e){ res.status(503).json({ok:false,service:'nonna-pizzaria-api',database:'unavailable'}); } });
app.get('/api/config',async(req,res)=>{const p=readToken((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!p?.rid)return res.json({service:'nonna-pizzaria-api',version:'1.1.0',migration:'supported'});try{const r=await q('SELECT data,updated_at FROM restaurant_config WHERE restaurant_id=$1',[p.rid]);res.json(r.rows[0]||{data:{}})}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/auth/register', async(req,res)=>{ const {restaurantName,name,email,password}=req.body||{}; if(!restaurantName||!name||!email||!password||password.length<8) return res.status(400).json({error:'restaurantName,name,email,password(min_8) required'}); const client=await pool.connect(); try { await ensureSchema(); await client.query('BEGIN'); const rid=id(),uid=id(); const r=await client.query('INSERT INTO restaurants(id,name) VALUES($1,$2) RETURNING id,name',[rid,String(restaurantName).trim()]); await client.query('INSERT INTO users(id,restaurant_id,email,name,role,password_hash) VALUES($1,$2,lower($3),$4,$5,$6)',[uid,rid,email.trim(),name.trim(),'owner',hashPassword(password)]); await client.query('COMMIT'); res.status(201).json({token:token({uid,rid,role:'owner'}),restaurant:r.rows[0],user:{id:uid,name,email:email.toLowerCase(),role:'owner'}}); } catch(e){ await client.query('ROLLBACK').catch(()=>{}); res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'email_exists':'registration_failed'}); } finally{client.release();} });
app.post('/api/auth/login', async(req,res)=>{ const {email,password}=req.body||{}; if(!email||!password) return res.status(400).json({error:'email,password required'}); try { const r=await q('SELECT id,restaurant_id,name,email,role,password_hash FROM users WHERE email=lower($1) AND active=true',[email]); const u=r.rows[0]; if(!u||!checkPassword(password,u.password_hash)) return res.status(401).json({error:'invalid_credentials'}); await q('UPDATE users SET last_access_at=now() WHERE id=$1',[u.id]); res.json({token:token({uid:u.id,rid:u.restaurant_id,role:u.role}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}); } catch { res.status(503).json({error:'database_unavailable'}); } });
app.get('/api/me',auth,async(req,res)=>{ try { const r=await q('SELECT u.id,u.name,u.email,u.role,r.id restaurant_id,r.name restaurant_name FROM users u JOIN restaurants r ON r.id=u.restaurant_id WHERE u.id=$1 AND u.restaurant_id=$2',[req.user.uid,req.user.rid]); if(!r.rowCount)return res.status(401).json({error:'unauthorized'}); res.json(r.rows[0]); } catch {res.status(503).json({error:'database_unavailable'});} });
// Tenant-scoped operational team. Never return password hashes.
app.get('/api/users',auth,manager,async(req,res)=>{try{const r=await q('SELECT id,name,email,role,active,created_at,last_access_at FROM users WHERE restaurant_id=$1 ORDER BY created_at ASC',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Staff accounts are created server-side so passwords are never exposed to Firebase/database writes.
app.post('/api/users',auth,manager,async(req,res)=>{
  const name=cleanText(req.body?.name,120), email=cleanText(req.body?.email,254).toLowerCase(), password=typeof req.body?.password==='string'?req.body.password:'', role=cleanText(req.body?.role,30);
  const allowed=['manager','cashier','kitchen','waiter','courier','staff'];
  if(!name||!/^\\S+@\\S+\\.\\S+$/.test(email)||password.length<8||!allowed.includes(role)) return res.status(400).json({error:'invalid_user_payload'});
  if(role==='manager'&&req.user.role!=='owner') return res.status(403).json({error:'forbidden'});
  try {
    const hash=await bcrypt.hash(password,12);
    const r=await q('INSERT INTO users(id,restaurant_id,email,name,role,password_hash,active) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING id,name,email,role,active,created_at,last_access_at',[id(),req.user.rid,email,name,role,hash]);
    await audit(req,'create','user',r.rows[0].id,{role});
    res.status(201).json(r.rows[0]);
  } catch(e) { res.status(e?.code==='23505'?409:400).json({error:e?.code==='23505'?'email_exists':'invalid_data'}); }
});
app.patch('/api/users/:id',auth,manager,async(req,res)=>{const role=req.body?.role===undefined?undefined:cleanText(req.body.role,30),active=req.body?.active===undefined?undefined:req.body.active===true;if(role!==undefined&&!['owner','manager','cashier','kitchen','waiter','courier','staff'].includes(role))return res.status(400).json({error:'invalid_role'});if(role==='owner'&&req.user.role!=='owner')return res.status(403).json({error:'forbidden'});if(String(req.params.id)===String(req.user.uid)&&active===false)return res.status(400).json({error:'cannot_disable_self'});try{const r=await q(`UPDATE users SET role=COALESCE($1,role),active=COALESCE($2,active) WHERE id=$3 AND restaurant_id=$4 RETURNING id,name,email,role,active,created_at,last_access_at`,[role,active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update','user',req.params.id,{role,active});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
for(const [route,[table,fields]] of Object.entries(listRoutes)){ const guard=route==='reservations'?staff:manager; app.get('/api/'+route,auth,staff,async(req,res)=>{try{const r=await q(`SELECT * FROM ${table} WHERE restaurant_id=$1 ORDER BY ${(table === 'products' || table === 'inventory') ? 'updated_at' : 'created_at'} DESC NULLS LAST`,[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}}); app.post('/api/'+route,auth,guard,async(req,res)=>{try{const vals=bodyFields(req.body||{},fields).map((v,i)=>['customer'].includes(fields[i])?json(v):v);if((table==='products'||table==='inventory'||table==='expenses')&&vals.some(v=>typeof v==='string'&&v.length>500))return res.status(400).json({error:'invalid_data'});const cols=['id','restaurant_id',...fields];const r=await q(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${cols.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,[id(),req.user.rid,...vals]);await audit(req,'create',route,r.rows[0].id);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'invalid_data'})}}); }
app.get('/api/products/public/:restaurantId',async(req,res)=>{try{const r=await q('SELECT id,category,name,description,price,emoji,image_url FROM products WHERE restaurant_id=$1 AND active=true ORDER BY category,name',[req.params.restaurantId]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.get('/api/orders',auth,async(req,res)=>{try{const r=await q('SELECT * FROM orders WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/orders',auth,async(req,res)=>{const b=req.body||{};if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)return res.status(400).json({error:'items_required'});const fee=num(b.delivery_fee,0);if(fee===null||fee>10000)return res.status(400).json({error:'invalid_delivery_fee'});const subtotal=Number(b.subtotal);const total=Number(b.total);if(!Number.isFinite(subtotal)||subtotal<0||!Number.isFinite(total)||total<0||Math.abs(total-(subtotal+fee))>0.01)return res.status(400).json({error:'invalid_totals'});try{const r=await q('INSERT INTO orders(id,restaurant_id,status,channel,customer,items,subtotal,delivery_fee,total,payment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id(),req.user.rid,b.status||'pending',cleanText(b.channel||'counter',30),json(b.customer),b.items,subtotal,fee,total,json(b.payment)]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_order'})}});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{const status=String(req.body?.status||'').trim();if(!['pending','preparing','ready','out_for_delivery','delivered','cancelled'].includes(status))return res.status(400).json({error:'invalid_status'});try{const c=await q('UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 RETURNING *',[status,req.params.id,req.user.rid]);if(!c.rowCount)return res.status(404).json({error:'not_found'});await q('INSERT INTO order_events(order_id,status,actor_id) VALUES($1,$2,$3)',[req.params.id,status,req.user.uid]);res.json(c.rows[0])}catch{res.status(400).json({error:'invalid_status'})}});
app.get('/api/orders/:id/events',auth,async(req,res)=>{try{const r=await q('SELECT e.* FROM order_events e JOIN orders o ON o.id=e.order_id WHERE e.order_id=$1 AND o.restaurant_id=$2 ORDER BY e.created_at',[req.params.id,req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Nonna operational API: all staff routes are tenant-scoped and role checked.
// Product/catalog CRUD
app.put('/api/products/:id',auth,manager,async(req,res)=>{const b=req.body||{};try{const r=await q(`UPDATE products SET category=COALESCE($1,category),name=COALESCE($2,name),description=$3,price=COALESCE($4,price),cost=COALESCE($5,cost),emoji=$6,image_url=$7,active=COALESCE($8,active),updated_at=now() WHERE id=$9 AND restaurant_id=$10 RETURNING *`,[b.category,b.name,b.description??null,num(b.price),num(b.cost),b.emoji??null,b.image_url??null,b.active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update','product',req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.delete('/api/products/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE products SET active=false,updated_at=now() WHERE id=$1 AND restaurant_id=$2 RETURNING id',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'archive','product',req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'invalid_data'})}});
app.post('/api/products/reset',auth,manager,async(req,res)=>{const products=Array.isArray(req.body?.products)?req.body.products:[];if(products.length>200)return res.status(400).json({error:'too_many_products'});const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');await c.query('UPDATE products SET active=false,updated_at=now() WHERE restaurant_id=$1',[req.user.rid]);for(const b of products){if(!cleanText(b.name,120))continue;await c.query('INSERT INTO products(id,restaurant_id,category,name,description,price,cost,emoji,image_url,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true)',[id(),req.user.rid,cleanText(b.category||'Geral',80),cleanText(b.name,120),cleanText(b.description,500)||null,num(b.price)||0,num(b.cost)||0,b.emoji||null,b.image_url||null])}await c.query('COMMIT');await audit(req,'reset','catalog',null,{count:products.length});res.json({ok:true,count:products.length})}catch{await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:'reset_failed'})}finally{c.release()}});
// Public checkout: validates tenant, item IDs/prices and supports replay-safe idempotency.
app.post('/api/public/orders',async(req,res)=>{const b=req.body||{},rid=cleanText(b.restaurantId||b.restaurant_id,100),items=Array.isArray(b.items)?b.items:[],key=cleanText(req.get('Idempotency-Key')||b.idempotencyKey,120);if(!rid||!items.length||items.length>100)return res.status(400).json({error:'restaurantId_and_items_required'});if(key){try{const old=await q('SELECT o.* FROM order_idempotency i JOIN orders o ON o.id=i.order_id WHERE i.restaurant_id=$1 AND i.key=$2',[rid,key]);if(old.rowCount)return res.status(200).json(old.rows[0])}catch{return res.status(503).json({error:'database_unavailable'})}}try{const ids=items.map(x=>String(x.productId||x.id||''));if(ids.some(x=>!x))return res.status(400).json({error:'invalid_items'});const pr=await q('SELECT id,name,price FROM products WHERE restaurant_id=$1 AND active=true AND id=ANY($2::text[])',[rid,ids]);const by=new Map(pr.rows.map(x=>[x.id,x]));if(pr.rowCount!==new Set(ids).size)return res.status(400).json({error:'product_unavailable'});const normalized=items.map(x=>{const p=by.get(String(x.productId||x.id));const qty=num(x.quantity??x.qty,1);if(!qty||qty>99)throw Error('qty');return {productId:p.id,name:p.name,price:Number(p.price),quantity:qty,notes:cleanText(x.notes,200)}});const subtotal=normalized.reduce((a,x)=>a+x.price*x.quantity,0),fee=num(b.delivery_fee,0)||0,total=subtotal+fee,oid=id();const c=await pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO orders(id,restaurant_id,status,channel,customer,items,subtotal,delivery_fee,total,payment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[oid,rid,'pending',cleanText(b.channel||'delivery',30),json(b.customer),normalized,subtotal,fee,total,json(b.payment)]);if(key)await c.query('INSERT INTO order_idempotency(restaurant_id,key,order_id) VALUES($1,$2,$3)',[rid,key,oid]);await c.query('INSERT INTO order_events(order_id,status,metadata) VALUES($1,$2,$3)',[oid,'pending',json({source:'public'})]);await c.query('COMMIT');const out=await q('SELECT * FROM orders WHERE id=$1',[oid]);res.status(201).json(out.rows[0])}catch(e){await c.query('ROLLBACK').catch(()=>{});if(e.code==='23505'&&key){const old=await q('SELECT o.* FROM order_idempotency i JOIN orders o ON o.id=i.order_id WHERE i.restaurant_id=$1 AND i.key=$2',[rid,key]);return res.json(old.rows[0])}res.status(400).json({error:'order_failed'})}finally{c.release()}}catch(e){res.status(400).json({error:e.message==='qty'?'invalid_quantity':'invalid_order'})}});
// Config
app.put('/api/config',auth,manager,async(req,res)=>{try{const data=req.body?.data??req.body??{};const r=await q(`INSERT INTO restaurant_config(restaurant_id,data,updated_at) VALUES($1,$2,now()) ON CONFLICT(restaurant_id) DO UPDATE SET data=EXCLUDED.data,updated_at=now() RETURNING data,updated_at`,[req.user.rid,data]);await audit(req,'update','config',req.user.rid);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_config'})}});
app.get('/api/config',async(req,res,next)=>{if(req.user)return next();res.json({service:'nonna-pizzaria-api',version:'1.1.0',migration:'supported'})});
app.get('/api/config/restaurant',auth,staff,async(req,res)=>{try{const r=await q('SELECT data,updated_at FROM restaurant_config WHERE restaurant_id=$1',[req.user.rid]);res.json(r.rows[0]||{data:{}})}catch{res.status(503).json({error:'database_unavailable'})}});
// Generic tenant CRUD for inventory, expenses and reservations.
for(const [path,table,fields,guard] of [['inventory','inventory',['name','category','quantity','min_quantity','unit'],manager],['expenses','expenses',['description','category','amount','due_date','paid'],manager],['reservations','reservations',['customer','table_no','starts_at','status'],staff]]){app.put('/api/'+path+'/:id',auth,guard,async(req,res)=>{const b=req.body||{},sets=fields.map((f,i)=>`${f}=$${i+1}`).join(',');const vals=fields.map(f=>f==='customer'?json(b[f]):b[f]);try{const r=await q(`UPDATE ${table} SET ${sets}${table==='inventory'?',updated_at=now()':''} WHERE id=$${fields.length+1} AND restaurant_id=$${fields.length+2} RETURNING *`,[...vals,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update',path,req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});app.delete('/api/'+path+'/:id',auth,guard,async(req,res)=>{try{const r=await q(`DELETE FROM ${table} WHERE id=$1 AND restaurant_id=$2 RETURNING id`,[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'delete',path,req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'delete_failed'})}})}
app.post('/api/inventory/:id/adjust',auth,manager,async(req,res)=>{const delta=num(req.body?.delta);if(delta===null)return res.status(400).json({error:'delta_required'});try{const r=await q('UPDATE inventory SET quantity=quantity+$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 AND quantity+$1>=0 RETURNING *',[delta,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(400).json({error:'invalid_adjustment'});await audit(req,'adjust','inventory',req.params.id,{delta});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_adjustment'})}});
// Cash register and movements. Only one open register per restaurant.
app.get('/api/cash/registers',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM cash_registers WHERE restaurant_id=$1 ORDER BY opened_at DESC NULLS LAST',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.get('/api/cash/register',auth,staff,async(req,res)=>{try{const r=await q("SELECT * FROM cash_registers WHERE restaurant_id=$1 AND status='open' ORDER BY opened_at DESC LIMIT 1",[req.user.rid]);res.json(r.rows[0]||null)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/cash/registers/open',auth,manager,async(req,res)=>{const opening=num(req.body?.opening,0)||0;const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');const open=await c.query("SELECT id FROM cash_registers WHERE restaurant_id=$1 AND status='open' FOR UPDATE",[req.user.rid]);if(open.rowCount){await c.query('ROLLBACK');return res.status(409).json({error:'register_already_open'})}const r=await c.query("INSERT INTO cash_registers(id,restaurant_id,status,opened_at,expected) VALUES($1,$2,'open',now(),$3) RETURNING *",[id(),req.user.rid,opening]);await c.query('COMMIT');await audit(req,'open','cash_register',r.rows[0].id);res.status(201).json(r.rows[0])}catch{await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:'open_failed'})}finally{c.release()}});
app.post('/api/cash/registers/:id/close',auth,manager,async(req,res)=>{const counted=num(req.body?.counted,0);if(counted===null)return res.status(400).json({error:'counted_required'});try{const r=await q("UPDATE cash_registers SET status='closed',closed_at=now(),counted=$1 WHERE id=$2 AND restaurant_id=$3 AND status='open' RETURNING *",[counted,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'close','cash_register',req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'close_failed'})}});
app.get('/api/cash/registers/:id/movements',auth,staff,async(req,res)=>{try{const r=await q('SELECT m.* FROM cash_movements m JOIN cash_registers c ON c.id=m.register_id WHERE m.register_id=$1 AND c.restaurant_id=$2 ORDER BY m.created_at DESC',[req.params.id,req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/cash/registers/:id/movements',auth,staff,async(req,res)=>{const amount=num(req.body?.amount,0),type=cleanText(req.body?.type,20);if(amount===null||!['in','out','sale','refund'].includes(type))return res.status(400).json({error:'invalid_movement'});try{const r=await q("WITH reg AS (SELECT id FROM cash_registers WHERE id=$1 AND restaurant_id=$2 AND status='open') INSERT INTO cash_movements(id,register_id,type,amount,description,actor_id) SELECT $3,id,$4,$5,$6,$7 FROM reg RETURNING *",[req.params.id,req.user.rid,id(),type,amount,cleanText(req.body?.description,200)||null,req.user.uid]);if(!r.rowCount)return res.status(404).json({error:'register_not_open'});await q("UPDATE cash_registers SET expected=expected+CASE WHEN $1 IN ('in','sale') THEN $2 ELSE -$2 END WHERE id=$3",[type,amount,req.params.id]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_movement'})}});
// Customer directory (tenant scoped; phone is the stable merge key).
app.get('/api/customers',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM customers WHERE restaurant_id=$1 ORDER BY updated_at DESC LIMIT 2000',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/customers',auth,staff,async(req,res)=>{const name=cleanText(req.body?.name,120),phone=cleanText(req.body?.phone,40);if(!name)return res.status(400).json({error:'name_required'});try{const r=await q(`INSERT INTO customers(id,restaurant_id,name,phone,email,address,notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(restaurant_id,phone) DO UPDATE SET name=EXCLUDED.name,email=EXCLUDED.email,address=EXCLUDED.address,notes=EXCLUDED.notes,updated_at=now() RETURNING *`,[id(),req.user.rid,name,phone||null,cleanText(req.body?.email,160)||null,json(req.body?.address),cleanText(req.body?.notes,500)||null]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_customer'})}});
app.put('/api/customers/:id',auth,staff,async(req,res)=>{try{const r=await q('UPDATE customers SET name=COALESCE($1,name),phone=COALESCE($2,phone),email=$3,address=$4,notes=$5,updated_at=now() WHERE id=$6 AND restaurant_id=$7 RETURNING *',[cleanText(req.body?.name,120)||null,cleanText(req.body?.phone,40)||null,cleanText(req.body?.email,160)||null,json(req.body?.address),cleanText(req.body?.notes,500)||null,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_customer'})}});
app.get('/api/audit',auth,manager,async(req,res)=>{try{const r=await q('SELECT * FROM audit_log WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Motoboys and last-known courier location
app.get('/api/motoboys',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM motoboys WHERE restaurant_id=$1 ORDER BY name',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/motoboys',auth,manager,async(req,res)=>{const name=cleanText(req.body?.name,120);if(!name)return res.status(400).json({error:'name_required'});try{const r=await q('INSERT INTO motoboys(id,restaurant_id,name,phone,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.user.rid,name,cleanText(req.body.phone,40)||null,req.body.active!==false]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.put('/api/motoboys/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE motoboys SET name=COALESCE($1,name),phone=$2,active=COALESCE($3,active) WHERE id=$4 AND restaurant_id=$5 RETURNING *',[cleanText(req.body?.name,120)||null,cleanText(req.body?.phone,40)||null,req.body?.active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.post('/api/motoboys/:id/location',auth,courierOrStaff,async(req,res)=>{const lat=num(req.body?.lat,-90),lng=num(req.body?.lng,-180);if(lat===null||lng===null||lat>90||lng>180)return res.status(400).json({error:'invalid_coordinates'});try{const own=await q('SELECT id FROM motoboys WHERE id=$1 AND restaurant_id=$2 AND active=true',[req.params.id,req.user.rid]);if(!own.rowCount)return res.status(404).json({error:'not_found'});const r=await q('INSERT INTO courier_locations(motoboy_id,restaurant_id,lat,lng,accuracy) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.id,req.user.rid,lat,lng,num(req.body.accuracy,0)]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_location'})}});
app.get('/api/motoboys/:id/location',auth,staff,async(req,res)=>{try{const r=await q('SELECT l.* FROM courier_locations l JOIN motoboys m ON m.id=l.motoboy_id WHERE l.motoboy_id=$1 AND l.restaurant_id=$2 ORDER BY l.created_at DESC LIMIT 1',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(503).json({error:'database_unavailable'})}});
const migrationAuthorized=req=>{const expected=process.env.MIGRATION_TOKEN;const supplied=req.get('x-migration-token')||(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!expected||!supplied||expected.length!==supplied.length)return false;return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied));};
const migrationGuard=(req,res,next)=>migrationAuthorized(req)?next():res.status(404).json({error:'not_found'});
let lastMigration=null;
app.post('/api/admin/migrate',migrationGuard,async(req,res)=>{try{const result=await migrateFirebase(req.body,pool);lastMigration={...result,completedAt:new Date().toISOString()};res.json(lastMigration);}catch(e){console.error('[migration]',e.message);res.status(500).json({ok:false,error:'migration_failed'});}});
app.post('/api/admin/migrate/owner',migrationGuard,async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const password=typeof req.body?.password==='string'?req.body.password:'';if(email!=='fabio08dejesusjunior@gmail.com'||password.length<8)return res.status(400).json({ok:false,error:'invalid_owner_payload'});const client=await pool.connect();try{await ensureSchema();await client.query('BEGIN');const claimed=await client.query(`INSERT INTO migration_state(key) VALUES('nonna-owner-credential-v6') ON CONFLICT(key) DO NOTHING RETURNING key`);if(!claimed.rowCount){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'owner_already_imported'});}const hash=await bcrypt.hash(password,12);const desiredUid='HaUqvQd6muYH3zUNUpwBOhD29Bf1';const existing=await client.query(`SELECT id FROM users WHERE restaurant_id=$1 AND lower(email)=lower($2) LIMIT 1`,['nonna-pizzaria',email]);const byUid=await client.query(`SELECT id FROM users WHERE id=$1`,[desiredUid]);if(existing.rows[0] && existing.rows[0].id!==desiredUid && !byUid.rowCount){await client.query(`UPDATE users SET id=$1 WHERE id=$2`,[desiredUid,existing.rows[0].id]);}else if(existing.rows[0] && existing.rows[0].id!==desiredUid && byUid.rowCount){await client.query(`DELETE FROM users WHERE id=$1`,[existing.rows[0].id]);}await client.query(`INSERT INTO users(id,restaurant_id,email,name,role,password_hash,active) VALUES($1,'nonna-pizzaria',$2,'Fabio Júnior','owner',$3,true) ON CONFLICT(id) DO UPDATE SET restaurant_id='nonna-pizzaria',email=EXCLUDED.email,name=EXCLUDED.name,role='owner',password_hash=EXCLUDED.password_hash,active=true`,[desiredUid,email,hash]);await client.query('COMMIT');res.json({ok:true,tenant:'nonna-pizzaria',userId:desiredUid,role:'owner',imported:true});}catch(e){await client.query('ROLLBACK').catch(()=>{});res.status(500).json({ok:false,error:'owner_import_failed'});}finally{client.release();}});
app.get('/api/admin/migrate/status',migrationGuard,async(_,res)=>{try{const r=await q(`SELECT json_build_object('restaurants',(SELECT count(*)::int FROM restaurants WHERE id='nonna-pizzaria'),'users',(SELECT count(*)::int FROM users WHERE restaurant_id='nonna-pizzaria'),'products',(SELECT count(*)::int FROM products WHERE restaurant_id='nonna-pizzaria'),'orders',(SELECT count(*)::int FROM orders WHERE restaurant_id='nonna-pizzaria')) AS counts`);res.json({ok:true,tenant:'nonna-pizzaria',counts:r.rows[0].counts,lastMigration});}catch{res.status(503).json({ok:false,error:'database_unavailable'});}});
app.use((_,res)=>res.status(404).json({error:'not_found'}));
const port=Number(process.env.PORT)||10000; app.listen(port,()=>console.log(`Nonna API listening on ${port}`));
process.on('SIGTERM',()=>pool.end().finally(()=>process.exit(0)));
