import express from 'express';
import cors from 'cors';
import pg from 'pg';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { migrateFirebase } from './migration-core.mjs';
const { Pool } = pg;
// Trusted custom-pizza pricing. Product rows are still required to be active in the
// tenant catalog; flavour rows currently carry price=0 because their price varies by size.
const CUSTOM_PIZZA_PRICES = Object.freeze({
 calabresa:{P:25,M:38,G:48},margherita:{P:28,M:42,G:52},quatro_queijos:{P:32,M:48,G:58},frango_catupiry:{P:28,M:42,G:52},portuguesa:{P:30,M:45,G:55},pepperoni:{P:35,M:50,G:62},bauru:{P:27,M:40,G:50},mineira:{P:32,M:46,G:58},chocolate:{P:26,M:38,G:48},banana:{P:24,M:35,G:44},romeu_julieta:{P:26,M:38,G:47},prestigio:{P:28,M:40,G:50}
});
const app = express();
app.disable('x-powered-by');
const corsOrigins = (process.env.CORS_ORIGIN || 'https://liderancaindigofabio-lab.github.io').split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({ origin(origin, cb) { if (!origin || corsOrigins.includes(origin)) return cb(null, true); return cb(new Error('cors_denied')); }, methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowedHeaders:['Content-Type','Authorization','Idempotency-Key','X-Migration-Token'] }));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');next();});
app.use(express.json({ limit: '256kb', strict: true }));
// JSON parsing happens before any route handler; reject malformed payloads explicitly
// so they cannot reach business mutations and clients receive a useful 400.
app.use((err, req, res, next) => {
  if (err?.type === 'entity.parse.failed') return res.status(400).json({ error: 'invalid_json' });
  if (err) return next(err);
  next();
});
// Small in-memory guard for the public/auth endpoints. It is intentionally bounded and
// complements (rather than replaces) a provider/WAF rate limit.
const requestBuckets = new Map();
function rateLimit(windowMs, max) { return (req, res, next) => {
  const now = Date.now(), key = `${req.ip}:${req.path}`;
  let b = requestBuckets.get(key); if (!b || now - b.start >= windowMs) b = { start: now, count: 0 };
  b.count++; requestBuckets.set(key, b);
  if (requestBuckets.size > 5000) for (const [k, v] of requestBuckets) if (now - v.start >= windowMs) requestBuckets.delete(k);
  if (b.count > max) return res.status(429).json({ error: 'rate_limited' });
  next();
}; }
app.use('/api/auth/login', rateLimit(60_000, 20));
app.use('/api/auth/register', rateLimit(60_000, 5));
app.use('/api/public/orders', rateLimit(60_000, 60));
const databaseUrl = process.env.DATABASE_URL;
const pool = new Pool({ connectionString: databaseUrl, ssl: databaseUrl ? { rejectUnauthorized:false } : false, max:5, connectionTimeoutMillis:3000, idleTimeoutMillis:10000 });
pool.on('error', e => console.error('[db]', e.message));
const secret = process.env.SESSION_SECRET || process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');
const schema = [
`CREATE TABLE IF NOT EXISTS restaurants(id text PRIMARY KEY,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),email text NOT NULL UNIQUE,name text NOT NULL,role text NOT NULL DEFAULT 'owner',password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),last_access_at timestamptz)`,
`CREATE TABLE IF NOT EXISTS products(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),category text NOT NULL DEFAULT 'Geral',name text NOT NULL,description text,price numeric(12,2) NOT NULL DEFAULT 0,cost numeric(12,2) NOT NULL DEFAULT 0,emoji text,image_url text,active boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS orders(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL DEFAULT 'pending',channel text,customer jsonb NOT NULL DEFAULT '{}',items jsonb NOT NULL DEFAULT '[]',subtotal numeric(12,2) NOT NULL DEFAULT 0,delivery_fee numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL DEFAULT 0,payment jsonb NOT NULL DEFAULT '{}',courier_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
`ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount numeric(12,2) NOT NULL DEFAULT 0 CHECK(discount>=0)`,
`CREATE TABLE IF NOT EXISTS order_events(id bigserial PRIMARY KEY,order_id text NOT NULL REFERENCES orders(id),status text NOT NULL,actor_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS inventory(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,category text,quantity numeric(12,3) NOT NULL DEFAULT 0,min_quantity numeric(12,3) NOT NULL DEFAULT 0,unit text NOT NULL DEFAULT 'un',updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS expenses(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),description text NOT NULL,category text,amount numeric(12,2) NOT NULL CHECK(amount>0),due_date date NOT NULL,paid boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS reservations(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),customer jsonb NOT NULL DEFAULT '{}',table_no text,starts_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'booked',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS cash_registers(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL,opened_at timestamptz,closed_at timestamptz,counted numeric(12,2),expected numeric(12,2))`,
`CREATE TABLE IF NOT EXISTS cash_movements(id text PRIMARY KEY,register_id text NOT NULL REFERENCES cash_registers(id),type text NOT NULL,amount numeric(12,2) NOT NULL CHECK(amount>0),description text,actor_id text,payment_method text,payment_breakdown jsonb,created_at timestamptz NOT NULL DEFAULT now())`,`ALTER TABLE cash_movements ADD COLUMN IF NOT EXISTS payment_method text`,`ALTER TABLE cash_movements ADD COLUMN IF NOT EXISTS payment_breakdown jsonb`,`CREATE TABLE IF NOT EXISTS migration_state(key text PRIMARY KEY,completed_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS restaurant_config(restaurant_id text PRIMARY KEY REFERENCES restaurants(id),data jsonb NOT NULL DEFAULT '{}',updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS motoboys(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,phone text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS courier_locations(id bigserial PRIMARY KEY,motoboy_id text NOT NULL REFERENCES motoboys(id),restaurant_id text NOT NULL REFERENCES restaurants(id),lat numeric(10,7) NOT NULL,lng numeric(10,7) NOT NULL,accuracy numeric(10,2),created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS customers(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,phone text,email text,address jsonb NOT NULL DEFAULT '{}',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(restaurant_id,phone))`,
`CREATE TABLE IF NOT EXISTS order_idempotency(restaurant_id text NOT NULL,key text NOT NULL,order_id text NOT NULL REFERENCES orders(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(restaurant_id,key))`,
`CREATE TABLE IF NOT EXISTS ingredients(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,unit text NOT NULL,cost_per_unit numeric(12,4) NOT NULL DEFAULT 0 CHECK(cost_per_unit>=0),stock_quantity numeric(14,4) NOT NULL DEFAULT 0 CHECK(stock_quantity>=0),min_quantity numeric(14,4) NOT NULL DEFAULT 0 CHECK(min_quantity>=0),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(restaurant_id,name))`,
`CREATE TABLE IF NOT EXISTS recipes(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),product_id text NOT NULL REFERENCES products(id),yield_quantity numeric(12,4) NOT NULL DEFAULT 1 CHECK(yield_quantity>0),yield_unit text NOT NULL,notes text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(restaurant_id,product_id))`,
`CREATE TABLE IF NOT EXISTS recipe_ingredients(id text PRIMARY KEY,recipe_id text NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,ingredient_id text NOT NULL REFERENCES ingredients(id),quantity numeric(12,4) NOT NULL CHECK(quantity>0),unit text NOT NULL,UNIQUE(recipe_id,ingredient_id))`,
`CREATE TABLE IF NOT EXISTS stock_movements(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),ingredient_id text NOT NULL REFERENCES ingredients(id),order_id text NOT NULL REFERENCES orders(id),quantity numeric(14,4) NOT NULL CHECK(quantity<0),reason text NOT NULL DEFAULT 'sale',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(order_id,ingredient_id))`,
`CREATE TABLE IF NOT EXISTS audit_log(id bigserial PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),actor_id text,action text NOT NULL,entity text,entity_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE UNIQUE INDEX IF NOT EXISTS cash_one_open_per_restaurant ON cash_registers(restaurant_id) WHERE status='open'`,
`CREATE INDEX IF NOT EXISTS orders_restaurant_created_idx ON orders(restaurant_id,created_at DESC)`,
`CREATE INDEX IF NOT EXISTS audit_restaurant_created_idx ON audit_log(restaurant_id,created_at DESC)`];
let schemaReady = false, schemaPromise;
const id = () => crypto.randomUUID();
const json = v => v === undefined ? {} : v;
function hashPassword(password){ const salt=crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`; }
function checkPassword(password, stored){ try { if(typeof stored==='string' && stored.startsWith('$2')) return bcrypt.compareSync(password,stored); const [salt,key]=stored.split(':'); return crypto.timingSafeEqual(crypto.scryptSync(password,salt,64),Buffer.from(key,'hex')); } catch { return false; } }
function token(payload){ const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url'); return `${body}.${crypto.createHmac('sha256',secret).update(body).digest('base64url')}`; }
function readToken(raw){ try { const [body,sig]=raw.split('.'); const good=crypto.createHmac('sha256',secret).update(body).digest('base64url'); if(!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good))) return null; const p=JSON.parse(Buffer.from(body,'base64url')); return p.exp>Date.now()?p:null; } catch { return null; } }
async function ensureSchema(){ if(schemaReady) return; if(!schemaPromise) schemaPromise=(async()=>{ if(!databaseUrl) throw new Error('DATABASE_URL missing'); for(const statement of schema) await pool.query(statement); schemaReady=true; })().catch(e=>{schemaPromise=null; throw e}); return schemaPromise; }
async function q(text, params=[]){ await ensureSchema(); return pool.query({text,values:params}); }
async function auth(req,res,next){ const p=readToken((req.headers.authorization||'').replace(/^Bearer\s+/i,'')); if(!p?.uid||!p?.rid) return res.status(401).json({error:'unauthorized'}); try { const r=await q('SELECT id,restaurant_id,role FROM users WHERE id=$1 AND restaurant_id=$2 AND active=true',[p.uid,p.rid]); if(!r.rowCount) return res.status(401).json({error:'unauthorized'}); req.user={...p,uid:r.rows[0].id,rid:r.rows[0].restaurant_id,role:r.rows[0].role}; next(); } catch { res.status(503).json({error:'database_unavailable'}); } }
function bodyFields(body, allowed){ return allowed.map(k=>body[k]); }
const roles = (...allowed) => (req,res,next) => allowed.includes(req.user?.role) ? next() : res.status(403).json({error:'forbidden'});
const staff = roles('owner','admin','manager','cashier','staff');
const manager = roles('owner','admin','manager');
const courierOrStaff = roles('owner','admin','manager','cashier','staff','courier');
const cleanText=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v,min=0)=>Number.isFinite(Number(v))&&Number(v)>=min?Number(v):null;
const signedNum=(v,limit=1000000)=>Number.isFinite(Number(v))&&Math.abs(Number(v))<=limit?Number(v):null;
async function audit(req,action,entity,entityId,metadata={}){ try{await q('INSERT INTO audit_log(restaurant_id,actor_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[req.user.rid,req.user.uid,action,entity,entityId,metadata]);}catch(e){console.error('[audit]',e.message)} }

const listRoutes = {
 products:['products',['category','name','description','price','cost','emoji','image_url','active']], inventory:['inventory',['name','category','quantity','min_quantity','unit']], expenses:['expenses',['description','category','amount','due_date','paid']], reservations:['reservations',['customer','table_no','starts_at','status']]
};
app.get('/health', async (_,res)=>{ try { await ensureSchema(); res.json({ok:true,service:'nonna-pizzaria-api',database:'connected'}); } catch(e){ res.status(503).json({ok:false,service:'nonna-pizzaria-api',database:'unavailable'}); } });
app.get('/api/config',async(req,res)=>{const p=readToken((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!p?.rid)return res.json({service:'nonna-pizzaria-api',version:'1.1.0',migration:'supported'});try{const r=await q('SELECT data,updated_at FROM restaurant_config WHERE restaurant_id=$1',[p.rid]);res.json(r.rows[0]||{data:{}})}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/auth/register', async(req,res)=>{ const {restaurantName,name,email,password}=req.body||{}; if(!restaurantName||!name||!email||!password||password.length<8) return res.status(400).json({error:'restaurantName,name,email,password(min_8) required'}); const client=await pool.connect(); try { await ensureSchema(); await client.query('BEGIN'); const rid=id(),uid=id(); const r=await client.query('INSERT INTO restaurants(id,name) VALUES($1,$2) RETURNING id,name',[rid,String(restaurantName).trim()]); await client.query('INSERT INTO users(id,restaurant_id,email,name,role,password_hash) VALUES($1,$2,lower($3),$4,$5,$6)',[uid,rid,email.trim(),name.trim(),'owner',hashPassword(password)]); await client.query('COMMIT'); res.status(201).json({token:token({uid,rid,role:'owner'}),restaurant:r.rows[0],user:{id:uid,name,email:email.toLowerCase(),role:'owner'}}); } catch(e){ await client.query('ROLLBACK').catch(()=>{}); res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'email_exists':'registration_failed'}); } finally{client.release();} });
app.post('/api/auth/login', async(req,res)=>{ const {email,password}=req.body||{}; if(!email||!password) return res.status(400).json({error:'email,password required'}); try { const r=await q('SELECT id,restaurant_id,name,email,role,password_hash FROM users WHERE email=lower($1) AND active=true',[email]); const u=r.rows[0]; if(!u||!checkPassword(password,u.password_hash)) return res.status(401).json({error:'invalid_credentials'}); await q('UPDATE users SET last_access_at=now() WHERE id=$1',[u.id]); res.json({token:token({uid:u.id,rid:u.restaurant_id,role:u.role}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}); } catch { res.status(503).json({error:'database_unavailable'}); } });
app.get('/api/me',auth,async(req,res)=>{ try { const r=await q('SELECT u.id,u.name,u.email,u.role,r.id restaurant_id,r.name restaurant_name FROM users u JOIN restaurants r ON r.id=u.restaurant_id WHERE u.id=$1 AND u.restaurant_id=$2',[req.user.uid,req.user.rid]); if(!r.rowCount)return res.status(401).json({error:'unauthorized'}); res.json(r.rows[0]); } catch {res.status(503).json({error:'database_unavailable'});} });
// Tenant-scoped operational team. Never return password hashes.
app.get('/api/users',auth,manager,async(req,res)=>{try{const r=await q('SELECT id,name,email,role,active,created_at,last_access_at FROM users WHERE restaurant_id=$1 ORDER BY created_at ASC',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Staff accounts are created server-side so passwords are never exposed to Firebase/database writes.
app.post('/api/users',auth,manager,async(req,res)=>{
  const name=cleanText(req.body?.name,120), email=cleanText(req.body?.email,254).toLowerCase(), password=typeof req.body?.password==='string'?req.body.password:'', role=cleanText(req.body?.role,30);
  const allowed=['manager','cashier','kitchen','waiter','courier','staff'];
  if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||!allowed.includes(role)) return res.status(400).json({error:'invalid_user_payload'});
  if(role==='manager'&&req.user.role!=='owner') return res.status(403).json({error:'forbidden'});
  try {
    const hash=await bcrypt.hash(password,12);
    const r=await q('INSERT INTO users(id,restaurant_id,email,name,role,password_hash,active) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING id,name,email,role,active,created_at,last_access_at',[id(),req.user.rid,email,name,role,hash]);
    await audit(req,'create','user',r.rows[0].id,{role});
    res.status(201).json(r.rows[0]);
  } catch(e) { res.status(e?.code==='23505'?409:400).json({error:e?.code==='23505'?'email_exists':'invalid_data'}); }
});
app.patch('/api/users/:id',auth,manager,async(req,res)=>{const role=req.body?.role===undefined?undefined:cleanText(req.body.role,30),active=req.body?.active===undefined?undefined:req.body.active===true;if(role!==undefined&&!['owner','manager','cashier','kitchen','waiter','courier','staff'].includes(role))return res.status(400).json({error:'invalid_role'});if(role==='owner'&&req.user.role!=='owner')return res.status(403).json({error:'forbidden'});if(String(req.params.id)===String(req.user.uid)&&active===false)return res.status(400).json({error:'cannot_disable_self'});try{const r=await q(`UPDATE users SET role=COALESCE($1,role),active=COALESCE($2,active) WHERE id=$3 AND restaurant_id=$4 RETURNING id,name,email,role,active,created_at,last_access_at`,[role,active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update','user',req.params.id,{role,active});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
for(const [route,[table,fields]] of Object.entries(listRoutes)){ const guard=route==='reservations'?staff:manager; app.get('/api/'+route,auth,staff,async(req,res)=>{try{const r=await q(`SELECT * FROM ${table} WHERE restaurant_id=$1 ORDER BY ${(table === 'products' || table === 'inventory') ? 'updated_at' : 'created_at'} DESC NULLS LAST`,[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}}); app.post('/api/'+route,auth,guard,async(req,res)=>{try{const vals=bodyFields(req.body||{},fields).map((v,i)=>['customer'].includes(fields[i])?json(v):v);if((table==='products'||table==='inventory'||table==='expenses')&&vals.some(v=>typeof v==='string'&&v.length>500))return res.status(400).json({error:'invalid_data'});const cols=['id','restaurant_id',...fields];const r=await q(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${cols.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,[id(),req.user.rid,...vals]);await audit(req,'create',route,r.rows[0].id);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'invalid_data'})}}); }
app.get('/api/products/public/:restaurantId',async(req,res)=>{try{const r=await q('SELECT id,category,name,description,price,emoji,image_url FROM products WHERE restaurant_id=$1 AND active=true ORDER BY category,name',[req.params.restaurantId]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.get('/api/orders',auth,async(req,res)=>{try{const r=await q('SELECT * FROM orders WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/orders',auth,staff,async(req,res)=>{const b=req.body||{},requestedStatus=String(b.status||'pending').trim();if(!['pending','preparing','ready','out_for_delivery','delivered','cancelled'].includes(requestedStatus))return res.status(400).json({error:'invalid_status'});if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)return res.status(400).json({error:'items_required'});const fee=num(b.delivery_fee,0);if(fee===null||fee>10000)return res.status(400).json({error:'invalid_delivery_fee'});const requestedDiscount=num(b.discount??b.desconto,0);if(requestedDiscount===null||requestedDiscount<0)return res.status(400).json({error:'invalid_discount'});if(requestedDiscount>0&&!['owner','manager'].includes(req.user.role))return res.status(403).json({error:'discount_requires_manager'});try{const ids=b.items.map(x=>String(x.productId??x.product_id??x.id??''));if(ids.some(x=>!x))return res.status(400).json({error:'invalid_items'});const pr=await q('SELECT id,name,price FROM products WHERE restaurant_id=$1 AND active=true AND id=ANY($2::text[])',[req.user.rid,[...new Set(ids)]]);const by=new Map(pr.rows.map(x=>[String(x.id),x]));if(by.size!==new Set(ids).size)return res.status(400).json({error:'product_unavailable'});const items=b.items.map(x=>{const product=by.get(String(x.productId??x.product_id??x.id));const quantity=num(x.quantity??x.qty,1);if(!quantity||quantity>99)throw new Error('invalid_quantity');return {...x,productId:String(product.id),name:product.name,price:Number(product.price),quantity};});const subtotal=Math.round(items.reduce((sum,x)=>sum+x.price*x.quantity,0)*100)/100;const discount=Math.min(subtotal,Math.round(requestedDiscount*100)/100);const total=Math.round((subtotal-discount+fee)*100)/100;const r=await q('INSERT INTO orders(id,restaurant_id,status,channel,customer,items,subtotal,delivery_fee,discount,total,payment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[id(),req.user.rid,requestedStatus,cleanText(b.channel||'counter',30),json(b.customer),items,subtotal,fee,discount,total,json(b.payment)]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message==='invalid_quantity'?'invalid_quantity':'invalid_order'})}});
async function deductOrderStock(client, restaurantId, orderId, items){
  const ids=[...new Set(items.map(x=>String(x.productId||x.id||'')))].filter(Boolean);
  if(!ids.length)return;
  const recipes=await client.query(`SELECT r.product_id,r.yield_quantity,ri.ingredient_id,ri.quantity,ri.unit,i.unit ingredient_unit FROM recipes r JOIN recipe_ingredients ri ON ri.recipe_id=r.id JOIN ingredients i ON i.id=ri.ingredient_id WHERE r.restaurant_id=$1 AND r.active=true AND i.active=true AND r.product_id=ANY($2::text[])`,[restaurantId,ids]);
  const totals=new Map();
  for(const item of items){const qty=positive(item.quantity??item.qty??1);if(!qty)throw Object.assign(new Error('invalid_quantity'),{code:'invalid_quantity'});for(const x of recipes.rows.filter(r=>r.product_id===String(item.productId||item.id))){const needed=convertQty(Number(x.quantity),x.unit,x.ingredient_unit)*qty/Number(x.yield_quantity);totals.set(x.ingredient_id,(totals.get(x.ingredient_id)||0)+needed);}}
  for(const [ingredientId,needed] of totals){const upd=await client.query('UPDATE ingredients SET stock_quantity=stock_quantity-$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 AND stock_quantity >= $1 RETURNING stock_quantity',[needed,ingredientId,restaurantId]);if(!upd.rowCount)throw Object.assign(new Error('insufficient_stock'),{code:'insufficient_stock'});await client.query(`INSERT INTO stock_movements(id,restaurant_id,ingredient_id,order_id,quantity,reason) VALUES($1,$2,$3,$4,$5,'sale')`,[id(),restaurantId,ingredientId,orderId,-needed]);}
}
app.patch('/api/orders/:id/status',auth,staff,async(req,res)=>{const status=String(req.body?.status||'').trim();if(!['pending','preparing','ready','out_for_delivery','delivered','cancelled'].includes(status))return res.status(400).json({error:'invalid_status'});const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');const current=await c.query('SELECT * FROM orders WHERE id=$1 AND restaurant_id=$2 FOR UPDATE',[req.params.id,req.user.rid]);if(!current.rowCount){await c.query('ROLLBACK');return res.status(404).json({error:'not_found'});}const old=current.rows[0];if(['delivered','cancelled'].includes(old.status)&&old.status!==status){await c.query('ROLLBACK');return res.status(409).json({error:'terminal_order'});}if(old.status===status){await c.query('ROLLBACK');return res.json(old);}if(status==='delivered')await deductOrderStock(c,req.user.rid,req.params.id,Array.isArray(old.items)?old.items:[]);const updated=await c.query('UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 RETURNING *',[status,req.params.id,req.user.rid]);await c.query('INSERT INTO order_events(order_id,status,actor_id,metadata) VALUES($1,$2,$3,$4)',[req.params.id,status,req.user.uid,status==='delivered'?{stockDeducted:true}:{}]);await c.query('COMMIT');res.json(updated.rows[0]);}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(e.code==='insufficient_stock'?409:e.code==='invalid_quantity'?400:400).json({error:e.code||'invalid_status'});}finally{c.release();}});
app.get('/api/orders/:id/events',auth,async(req,res)=>{try{const r=await q('SELECT e.* FROM order_events e JOIN orders o ON o.id=e.order_id WHERE e.order_id=$1 AND o.restaurant_id=$2 ORDER BY e.created_at',[req.params.id,req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Nonna operational API: all staff routes are tenant-scoped and role checked.
// Product/catalog CRUD
app.put('/api/products/:id',auth,manager,async(req,res)=>{const b=req.body||{};try{const r=await q(`UPDATE products SET category=COALESCE($1,category),name=COALESCE($2,name),description=$3,price=COALESCE($4,price),cost=COALESCE($5,cost),emoji=$6,image_url=$7,active=COALESCE($8,active),updated_at=now() WHERE id=$9 AND restaurant_id=$10 RETURNING *`,[b.category,b.name,b.description??null,num(b.price),num(b.cost),b.emoji??null,b.image_url??null,b.active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update','product',req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.delete('/api/products/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE products SET active=false,updated_at=now() WHERE id=$1 AND restaurant_id=$2 RETURNING id',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'archive','product',req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'invalid_data'})}});
app.post('/api/products/reset',auth,manager,async(req,res)=>{const products=Array.isArray(req.body?.products)?req.body.products:[];if(products.length>200)return res.status(400).json({error:'too_many_products'});const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');await c.query('UPDATE products SET active=false,updated_at=now() WHERE restaurant_id=$1',[req.user.rid]);for(const b of products){if(!cleanText(b.name,120))continue;await c.query('INSERT INTO products(id,restaurant_id,category,name,description,price,cost,emoji,image_url,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true)',[id(),req.user.rid,cleanText(b.category||'Geral',80),cleanText(b.name,120),cleanText(b.description,500)||null,num(b.price)||0,num(b.cost)||0,b.emoji||null,b.image_url||null])}await c.query('COMMIT');await audit(req,'reset','catalog',null,{count:products.length});res.json({ok:true,count:products.length})}catch{await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:'reset_failed'})}finally{c.release()}});
// Public checkout: validates tenant, item IDs/prices and supports replay-safe idempotency.
app.post('/api/public/orders',async(req,res)=>{const b=req.body||{},rid=cleanText(b.restaurantId||b.restaurant_id,100),items=Array.isArray(b.items)?b.items:[],key=cleanText(req.get('Idempotency-Key')||b.idempotencyKey,120);if(!rid||!items.length||items.length>100)return res.status(400).json({error:'restaurantId_and_items_required'});if(key){try{const old=await q('SELECT o.* FROM order_idempotency i JOIN orders o ON o.id=i.order_id WHERE i.restaurant_id=$1 AND i.key=$2',[rid,key]);if(old.rowCount)return res.status(200).json(old.rows[0])}catch{return res.status(503).json({error:'database_unavailable'})}}try{const ids=[];for(const x of items){const custom=x.customPizza&&typeof x.customPizza==='object'?x.customPizza:null;ids.push(String(x.productId||x.id||''));if(custom){ids.push(String(custom.sizeId??custom.size_id??''));for(const k of ['flavours','sabores','addons','adicionais'])if(Array.isArray(custom[k]))ids.push(...custom[k].map(v=>String(v?.id??v)));}}if(ids.some(x=>!x))return res.status(400).json({error:'invalid_items'});const pr=await q('SELECT id,name,price,category,active FROM products WHERE restaurant_id=$1 AND active=true AND id=ANY($2::text[])',[rid,[...new Set(ids)]]);const by=new Map(pr.rows.map(x=>[String(x.id),x]));if(pr.rowCount!==new Set(ids).size)return res.status(400).json({error:'product_unavailable'});const normalized=items.map(x=>{
const rawId=String(x.productId||x.id||''); const custom=x.customPizza&&typeof x.customPizza==='object'?x.customPizza:null;
const qty=num(x.quantity??x.qty,1); if(!Number.isInteger(qty)||qty<1||qty>99)throw Error('qty');
if(custom){
 const sizeId=cleanText(custom.sizeId??custom.size_id,40), flavours=Array.isArray(custom.flavours??custom.sabores)?(custom.flavours??custom.sabores):[], addons=Array.isArray(custom.addons??custom.adicionais)?(custom.addons??custom.adicionais):[];
 if(!sizeId||flavours.length<1||flavours.length>2||addons.length>10)throw Error('custom');
 const ids=[sizeId,...flavours.map(v=>String(v?.id??v)),...addons.map(v=>String(v?.id??v))];
 const rows=ids.map(id=>by.get(id)); if(rows.some(r=>!r))throw Error('product_unavailable');
 const size=by.get(sizeId); if(size.category!=='tamanhos'||!['P','M','G'].includes(sizeId))throw Error('custom_catalog');
 const fs=flavours.map(v=>by.get(String(v?.id??v))); const ads=addons.map(v=>by.get(String(v?.id??v)));
 if(fs.some(r=>r.category!=='sabores'||!r.active)||ads.some(r=>r.category!=='adicionais'||!r.active))throw Error('custom');
 const maxFlavours=sizeId==='P'?1:2; if(flavours.length>maxFlavours)throw Error('custom');
 const flavourPrice=Math.max(...fs.map(r=>Number(CUSTOM_PIZZA_PRICES[r.id]?.[sizeId]||0))); const addonPrice=ads.reduce((a,r)=>a+Number(r.price),0);
 if(!Number.isFinite(flavourPrice)||flavourPrice<=0)throw Error('custom_catalog');
 const composition={category:'pizza',size:{id:size.id,name:size.name},flavours:fs.map(r=>({id:r.id,name:r.name})),addons:ads.map(r=>({id:r.id,name:r.name})),observations:cleanText(custom.observations??custom.observacao,500)};
 return {productId:size.id,name:`Pizza ${size.name}`,price:Math.round((flavourPrice+addonPrice)*100)/100,quantity:qty,notes:composition.observations,category:'pizza',composition};
}
const p=by.get(rawId); if(!p)throw Error('product_unavailable'); return {productId:p.id,name:p.name,price:Number(p.price),quantity:qty,notes:cleanText(x.notes,200),category:p.category};
});const subtotal=normalized.reduce((a,x)=>a+x.price*x.quantity,0),fee=num(b.delivery_fee,0);if(fee===null||fee>10000)return res.status(400).json({error:'invalid_delivery_fee'});const total=subtotal+fee,oid=id();const c=await pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO orders(id,restaurant_id,status,channel,customer,items,subtotal,delivery_fee,total,payment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[oid,rid,'pending',cleanText(b.channel||'delivery',30),json(b.customer),normalized,subtotal,fee,total,json(b.payment)]);if(key)await c.query('INSERT INTO order_idempotency(restaurant_id,key,order_id) VALUES($1,$2,$3)',[rid,key,oid]);await c.query('INSERT INTO order_events(order_id,status,metadata) VALUES($1,$2,$3)',[oid,'pending',json({source:'public'})]);await c.query('COMMIT');const out=await q('SELECT * FROM orders WHERE id=$1',[oid]);res.status(201).json(out.rows[0])}catch(e){await c.query('ROLLBACK').catch(()=>{});if(e.code==='23505'&&key){const old=await q('SELECT o.* FROM order_idempotency i JOIN orders o ON o.id=i.order_id WHERE i.restaurant_id=$1 AND i.key=$2',[rid,key]);return res.json(old.rows[0])}res.status(400).json({error:'order_failed'})}finally{c.release()}}catch(e){res.status(400).json({error:e.message==='qty'?'invalid_quantity':'invalid_order'})}});
// Config
app.put('/api/config',auth,manager,async(req,res)=>{try{const data=req.body?.data??req.body??{};const r=await q(`INSERT INTO restaurant_config(restaurant_id,data,updated_at) VALUES($1,$2,now()) ON CONFLICT(restaurant_id) DO UPDATE SET data=EXCLUDED.data,updated_at=now() RETURNING data,updated_at`,[req.user.rid,data]);await audit(req,'update','config',req.user.rid);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_config'})}});
app.get('/api/config',async(req,res,next)=>{if(req.user)return next();res.json({service:'nonna-pizzaria-api',version:'1.1.0',migration:'supported'})});
app.get('/api/config/restaurant',auth,staff,async(req,res)=>{try{const r=await q('SELECT data,updated_at FROM restaurant_config WHERE restaurant_id=$1',[req.user.rid]);res.json(r.rows[0]||{data:{}})}catch{res.status(503).json({error:'database_unavailable'})}});
// Generic tenant CRUD for inventory, expenses and reservations.
for(const [path,table,fields,guard] of [['inventory','inventory',['name','category','quantity','min_quantity','unit'],manager],['expenses','expenses',['description','category','amount','due_date','paid'],manager],['reservations','reservations',['customer','table_no','starts_at','status'],staff]]){app.put('/api/'+path+'/:id',auth,guard,async(req,res)=>{const b=req.body||{},sets=fields.map((f,i)=>`${f}=$${i+1}`).join(',');const vals=fields.map(f=>f==='customer'?json(b[f]):b[f]);try{const r=await q(`UPDATE ${table} SET ${sets}${table==='inventory'?',updated_at=now()':''} WHERE id=$${fields.length+1} AND restaurant_id=$${fields.length+2} RETURNING *`,[...vals,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update',path,req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});app.delete('/api/'+path+'/:id',auth,guard,async(req,res)=>{try{const r=await q(`DELETE FROM ${table} WHERE id=$1 AND restaurant_id=$2 RETURNING id`,[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'delete',path,req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'delete_failed'})}})}
app.post('/api/inventory/:id/adjust',auth,manager,async(req,res)=>{const delta=signedNum(req.body?.delta);if(delta===null)return res.status(400).json({error:'delta_required'});try{const r=await q('UPDATE inventory SET quantity=quantity+$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 AND quantity+$1>=0 RETURNING *',[delta,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(400).json({error:'invalid_adjustment'});await audit(req,'adjust','inventory',req.params.id,{delta});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_adjustment'})}});
// Recipes and ingredients (owner/manager only). Quantities are positive and units are explicit.
const STOCK_UNITS = new Set(['g','kg','ml','l','un','unit']);
const unitInfo = {g:['mass',1],kg:['mass',1000],ml:['volume',1],l:['volume',1000],un:['count',1],unit:['count',1]};
function validUnit(v){const u=cleanText(v,12).toLowerCase();return STOCK_UNITS.has(u)?u:null;}
function positive(v){return Number.isFinite(Number(v))&&Number(v)>0&&Number(v)<=1000000?Number(v):null;}
function nonnegative(v){return Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=100000000?Number(v):null;}
function compatible(a,b){return unitInfo[a]&&unitInfo[b]&&unitInfo[a][0]===unitInfo[b][0];}
function convertQty(value,from,to){if(!compatible(from,to))return null;return value*unitInfo[from][1]/unitInfo[to][1];}
app.get('/api/ingredients',auth,manager,async(req,res)=>{try{const r=await q('SELECT * FROM ingredients WHERE restaurant_id=$1 ORDER BY name',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/ingredients',auth,manager,async(req,res)=>{const name=cleanText(req.body?.name,120),unit=validUnit(req.body?.unit),cost=nonnegative(req.body?.costPerUnit??req.body?.cost_per_unit),stock=nonnegative(req.body?.stockQuantity??req.body?.stock_quantity??0),min=nonnegative(req.body?.minQuantity??req.body?.min_quantity??0);if(!name||!unit||cost===null||stock===null||min===null)return res.status(400).json({error:'invalid_ingredient'});try{const r=await q('INSERT INTO ingredients(id,restaurant_id,name,unit,cost_per_unit,stock_quantity,min_quantity) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[id(),req.user.rid,name,unit,cost,stock,min]);await audit(req,'create','ingredient',r.rows[0].id);res.status(201).json(r.rows[0])}catch(e){res.status(e?.code==='23505'?409:400).json({error:e?.code==='23505'?'ingredient_exists':'invalid_ingredient'})}});
app.put('/api/ingredients/:id',auth,manager,async(req,res)=>{const b=req.body||{},name=b.name===undefined?null:cleanText(b.name,120),unit=b.unit===undefined?null:validUnit(b.unit),cost=b.costPerUnit===undefined&&b.cost_per_unit===undefined?null:nonnegative(b.costPerUnit??b.cost_per_unit),stock=b.stockQuantity===undefined&&b.stock_quantity===undefined?null:nonnegative(b.stockQuantity??b.stock_quantity),min=b.minQuantity===undefined&&b.min_quantity===undefined?null:nonnegative(b.minQuantity??b.min_quantity),active=b.active===undefined?null:b.active===true;if(b.name!==undefined&&!name||b.unit!==undefined&&!unit||cost===null&&('costPerUnit'in b||'cost_per_unit'in b)||stock===null&&('stockQuantity'in b||'stock_quantity'in b)||min===null&&('minQuantity'in b||'min_quantity'in b))return res.status(400).json({error:'invalid_ingredient'});try{const r=await q('UPDATE ingredients SET name=COALESCE($1,name),unit=COALESCE($2,unit),cost_per_unit=COALESCE($3,cost_per_unit),stock_quantity=COALESCE($4,stock_quantity),min_quantity=COALESCE($5,min_quantity),active=COALESCE($6,active),updated_at=now() WHERE id=$7 AND restaurant_id=$8 RETURNING *',[name,unit,cost,stock,min,active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'update','ingredient',req.params.id);res.json(r.rows[0])}catch(e){res.status(400).json({error:'invalid_ingredient'})}});
app.delete('/api/ingredients/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE ingredients SET active=false,updated_at=now() WHERE id=$1 AND restaurant_id=$2 RETURNING id',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'archive','ingredient',req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'invalid_data'})}});
async function saveRecipe(req,res){const b=req.body||{},productId=cleanText(b.productId??b.product_id,100),yieldQuantity=positive(b.yieldQuantity??b.yield_quantity??1),yieldUnit=validUnit(b.yieldUnit??b.yield_unit??'un'),items=Array.isArray(b.ingredients)?b.ingredients:[];if(!productId||yieldQuantity===null||!yieldUnit||items.length>200)return res.status(400).json({error:'invalid_recipe'});const parsed=items.map(x=>({ingredientId:cleanText(x.ingredientId??x.ingredient_id,100),quantity:positive(x.quantity),unit:validUnit(x.unit)}));if(parsed.some(x=>!x.ingredientId||x.quantity===null||!x.unit||parsed.filter(y=>y.ingredientId===x.ingredientId).length>1))return res.status(400).json({error:'invalid_recipe_ingredient'});const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');const product=await c.query('SELECT id FROM products WHERE id=$1 AND restaurant_id=$2',[productId,req.user.rid]);if(!product.rowCount){await c.query('ROLLBACK');return res.status(400).json({error:'product_not_found'})}const ir=await c.query('SELECT id,unit FROM ingredients WHERE restaurant_id=$1 AND id=ANY($2::text[])',[req.user.rid,parsed.map(x=>x.ingredientId)]);const by=new Map(ir.rows.map(x=>[x.id,x]));if(ir.rowCount!==parsed.length||parsed.some(x=>!compatible(x.unit,by.get(x.ingredientId).unit))){await c.query('ROLLBACK');return res.status(400).json({error:'incompatible_unit'})}const old=await c.query('SELECT id FROM recipes WHERE product_id=$1 AND restaurant_id=$2',[productId,req.user.rid]);let recipeId=old.rows[0]?.id;if(recipeId)await c.query('UPDATE recipes SET yield_quantity=$1,yield_unit=$2,notes=$3,active=true,updated_at=now() WHERE id=$4',[yieldQuantity,yieldUnit,cleanText(b.notes,500)||null,recipeId]);else {recipeId=id();await c.query('INSERT INTO recipes(id,restaurant_id,product_id,yield_quantity,yield_unit,notes) VALUES($1,$2,$3,$4,$5,$6)',[recipeId,req.user.rid,productId,yieldQuantity,yieldUnit,cleanText(b.notes,500)||null]);}await c.query('DELETE FROM recipe_ingredients WHERE recipe_id=$1',[recipeId]);for(const x of parsed)await c.query('INSERT INTO recipe_ingredients(id,recipe_id,ingredient_id,quantity,unit) VALUES($1,$2,$3,$4,$5)',[id(),recipeId,x.ingredientId,x.quantity,x.unit]);await c.query('COMMIT');await audit(req,old.rowCount?'update':'create','recipe',recipeId);const out=await q('SELECT r.*,p.name product_name,COALESCE(json_agg(json_build_object(\'ingredientId\',ri.ingredient_id,\'quantity\',ri.quantity,\'unit\',ri.unit)) FILTER (WHERE ri.id IS NOT NULL),\'[]\') ingredients FROM recipes r JOIN products p ON p.id=r.product_id LEFT JOIN recipe_ingredients ri ON ri.recipe_id=r.id WHERE r.id=$1 GROUP BY r.id,p.name',[recipeId]);res.status(old.rowCount?200:201).json(out.rows[0])}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:'invalid_recipe'})}finally{c.release()}}
app.get('/api/recipes',auth,manager,async(req,res)=>{try{const r=await q("SELECT r.*,p.name product_name,COALESCE(json_agg(json_build_object('ingredientId',ri.ingredient_id,'quantity',ri.quantity,'unit',ri.unit)) FILTER (WHERE ri.id IS NOT NULL),'[]') ingredients FROM recipes r JOIN products p ON p.id=r.product_id LEFT JOIN recipe_ingredients ri ON ri.recipe_id=r.id WHERE r.restaurant_id=$1 GROUP BY r.id,p.name ORDER BY p.name",[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/recipes',auth,manager,saveRecipe);app.put('/api/recipes/:id',auth,manager,async(req,res)=>{req.body={...(req.body||{})};const existing=await q('SELECT product_id FROM recipes WHERE id=$1 AND restaurant_id=$2',[req.params.id,req.user.rid]);if(!existing.rowCount)return res.status(404).json({error:'not_found'});req.body.productId=existing.rows[0].product_id;return saveRecipe(req,res)});
app.delete('/api/recipes/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE recipes SET active=false,updated_at=now() WHERE id=$1 AND restaurant_id=$2 RETURNING id',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'archive','recipe',req.params.id);res.json({ok:true})}catch{res.status(400).json({error:'invalid_data'})}});

// Cash register and movements. Only one open register per restaurant.
app.get('/api/cash/registers',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM cash_registers WHERE restaurant_id=$1 ORDER BY opened_at DESC NULLS LAST',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.get('/api/cash/register',auth,staff,async(req,res)=>{try{const r=await q("SELECT c.*,COALESCE((SELECT json_agg(m ORDER BY m.created_at ASC) FROM cash_movements m WHERE m.register_id=c.id),'[]'::json) AS movimentos FROM cash_registers c WHERE c.restaurant_id=$1 AND c.status='open' ORDER BY c.opened_at DESC LIMIT 1",[req.user.rid]);res.json(r.rows[0]||null)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/cash/registers/open',auth,manager,async(req,res)=>{const opening=num(req.body?.opening,0)||0;const c=await pool.connect();try{await ensureSchema();await c.query('BEGIN');const open=await c.query("SELECT id FROM cash_registers WHERE restaurant_id=$1 AND status='open' FOR UPDATE",[req.user.rid]);if(open.rowCount){await c.query('ROLLBACK');return res.status(409).json({error:'register_already_open'})}const r=await c.query("INSERT INTO cash_registers(id,restaurant_id,status,opened_at,expected) VALUES($1,$2,'open',now(),$3) RETURNING *",[id(),req.user.rid,opening]);await c.query('COMMIT');await audit(req,'open','cash_register',r.rows[0].id);res.status(201).json(r.rows[0])}catch{await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:'open_failed'})}finally{c.release()}});
app.post('/api/cash/registers/:id/close',auth,manager,async(req,res)=>{const counted=num(req.body?.counted,0);if(counted===null)return res.status(400).json({error:'counted_required'});try{const r=await q("UPDATE cash_registers SET status='closed',closed_at=now(),counted=$1 WHERE id=$2 AND restaurant_id=$3 AND status='open' RETURNING *",[counted,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req,'close','cash_register',req.params.id);res.json(r.rows[0])}catch{res.status(400).json({error:'close_failed'})}});
app.get('/api/cash/registers/:id/movements',auth,staff,async(req,res)=>{try{const r=await q('SELECT m.* FROM cash_movements m JOIN cash_registers c ON c.id=m.register_id WHERE m.register_id=$1 AND c.restaurant_id=$2 ORDER BY m.created_at DESC',[req.params.id,req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
function paymentData(body, amount) {
  const allowed = new Set(['dinheiro','pix','debito','credito']);
  const method = body?.payment_method == null ? null : cleanText(body.payment_method,20).toLowerCase();
  const raw = body?.payment_breakdown;
  if (method !== null && method !== 'misto' && !allowed.has(method)) return {error:'invalid_payment_method'};
  if (raw !== undefined && (raw === null || typeof raw !== 'object' || Array.isArray(raw))) return {error:'invalid_payment_breakdown'};
  const breakdown = raw === undefined ? null : {};
  if (breakdown) { for (const [key,value] of Object.entries(raw)) { if (!allowed.has(key) || !Number.isFinite(Number(value)) || Number(value) < 0) return {error:'invalid_payment_breakdown'}; const cents=Math.round(Number(value)*100); if(cents>0) breakdown[key]=cents/100; else delete breakdown[key]; } const sum=Math.round(Object.values(breakdown).reduce((a,v)=>a+Number(v)*100,0)); if(sum!==Math.round(Number(amount)*100)) return {error:'payment_breakdown_mismatch'}; }
  if (method === 'misto' && !breakdown) return {error:'payment_breakdown_required'};
  if (breakdown && method !== 'misto' && Object.keys(breakdown).length !== 1) return {error:'payment_method_mismatch'};
  return {method,breakdown};
}
app.post('/api/cash/registers/:id/movements',auth,staff,async(req,res)=>{const amount=num(req.body?.amount,0),type=cleanText(req.body?.type,20),payment=paymentData(req.body||{},amount);if(amount===null||!['in','out','sale','refund'].includes(type))return res.status(400).json({error:'invalid_movement'});if(payment.error)return res.status(400).json({error:payment.error});try{const r=await q("WITH reg AS (SELECT id FROM cash_registers WHERE id=$1 AND restaurant_id=$2 AND status='open') INSERT INTO cash_movements(id,register_id,type,amount,description,actor_id,payment_method,payment_breakdown) SELECT $3,id,$4,$5,$6,$7,$8,$9 FROM reg RETURNING *",[req.params.id,req.user.rid,id(),type,amount,cleanText(req.body?.description,200)||null,req.user.uid,payment.method,payment.breakdown]);if(!r.rowCount)return res.status(404).json({error:'register_not_open'});await q("UPDATE cash_registers SET expected=expected+CASE WHEN $1 IN ('in','sale') THEN $2 ELSE -$2 END WHERE id=$3",[type,amount,req.params.id]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_movement'})}});
// Customer directory (tenant scoped; phone is the stable merge key).
app.get('/api/customers',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM customers WHERE restaurant_id=$1 ORDER BY updated_at DESC LIMIT 2000',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/customers',auth,staff,async(req,res)=>{const name=cleanText(req.body?.name,120),phone=cleanText(req.body?.phone,40);if(!name)return res.status(400).json({error:'name_required'});try{const r=await q(`INSERT INTO customers(id,restaurant_id,name,phone,email,address,notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(restaurant_id,phone) DO UPDATE SET name=EXCLUDED.name,email=EXCLUDED.email,address=EXCLUDED.address,notes=EXCLUDED.notes,updated_at=now() RETURNING *`,[id(),req.user.rid,name,phone||null,cleanText(req.body?.email,160)||null,json(req.body?.address),cleanText(req.body?.notes,500)||null]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_customer'})}});
app.put('/api/customers/:id',auth,staff,async(req,res)=>{try{const r=await q('UPDATE customers SET name=COALESCE($1,name),phone=COALESCE($2,phone),email=$3,address=$4,notes=$5,updated_at=now() WHERE id=$6 AND restaurant_id=$7 RETURNING *',[cleanText(req.body?.name,120)||null,cleanText(req.body?.phone,40)||null,cleanText(req.body?.email,160)||null,json(req.body?.address),cleanText(req.body?.notes,500)||null,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_customer'})}});
app.get('/api/audit',auth,manager,async(req,res)=>{try{const r=await q('SELECT * FROM audit_log WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
// Motoboys and last-known courier location
app.get('/api/motoboys',auth,staff,async(req,res)=>{try{const r=await q('SELECT * FROM motoboys WHERE restaurant_id=$1 ORDER BY name',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/motoboys',auth,manager,async(req,res)=>{const name=cleanText(req.body?.name,120);if(!name)return res.status(400).json({error:'name_required'});try{const r=await q('INSERT INTO motoboys(id,restaurant_id,name,phone,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.user.rid,name,cleanText(req.body.phone,40)||null,req.body.active!==false]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.put('/api/motoboys/:id',auth,manager,async(req,res)=>{try{const r=await q('UPDATE motoboys SET name=COALESCE($1,name),phone=$2,active=COALESCE($3,active) WHERE id=$4 AND restaurant_id=$5 RETURNING *',[cleanText(req.body?.name,120)||null,cleanText(req.body?.phone,40)||null,req.body?.active,req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(400).json({error:'invalid_data'})}});
app.post('/api/motoboys/:id/location',auth,courierOrStaff,async(req,res)=>{const lat=num(req.body?.lat,-90),lng=num(req.body?.lng,-180);if(lat===null||lng===null||lat>90||lng>180)return res.status(400).json({error:'invalid_coordinates'});try{const own=await q('SELECT id FROM motoboys WHERE id=$1 AND restaurant_id=$2 AND active=true',[req.params.id,req.user.rid]);if(!own.rowCount)return res.status(404).json({error:'not_found'});const r=await q('INSERT INTO courier_locations(motoboy_id,restaurant_id,lat,lng,accuracy) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.id,req.user.rid,lat,lng,num(req.body.accuracy,0)]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_location'})}});
app.get('/api/motoboys/:id/location',auth,staff,async(req,res)=>{try{const r=await q('SELECT l.* FROM courier_locations l JOIN motoboys m ON m.id=l.motoboy_id WHERE l.motoboy_id=$1 AND l.restaurant_id=$2 ORDER BY l.created_at DESC LIMIT 1',[req.params.id,req.user.rid]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])}catch{res.status(503).json({error:'database_unavailable'})}});
const migrationAuthorized=req=>{const expected=process.env.MIGRATION_TOKEN;const supplied=req.get('x-migration-token')||(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!expected||!supplied||expected.length!==supplied.length)return false;return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied));};
const migrationGuard=(req,res,next)=>migrationAuthorized(req)?next():res.status(404).json({error:'not_found'});
let lastMigration=null;
app.post('/api/admin/migrate',migrationGuard,async(req,res)=>{try{const result=await migrateFirebase(req.body,pool);lastMigration={...result,completedAt:new Date().toISOString()};res.json(lastMigration);}catch(e){console.error('[migration]',e.message);res.status(500).json({ok:false,error:'migration_failed'});}});
app.post('/api/admin/migrate/owner',migrationGuard,async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const password=typeof req.body?.password==='string'?req.body.password:'';if(email!=='fabio08dejesusjunior@gmail.com'||password.length<8)return res.status(400).json({ok:false,error:'invalid_owner_payload'});const client=await pool.connect();try{await ensureSchema();await client.query('BEGIN');const claimed=await client.query(`INSERT INTO migration_state(key) VALUES('nonna-owner-credential-v6') ON CONFLICT(key) DO NOTHING RETURNING key`);if(!claimed.rowCount){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'owner_already_imported'});}const hash=await bcrypt.hash(password,12);const desiredUid='HaUqvQd6muYH3zUNUpwBOhD29Bf1';const existing=await client.query(`SELECT id FROM users WHERE restaurant_id=$1 AND lower(email)=lower($2) LIMIT 1`,['nonna-pizzaria',email]);const byUid=await client.query(`SELECT id FROM users WHERE id=$1`,[desiredUid]);if(existing.rows[0] && existing.rows[0].id!==desiredUid && !byUid.rowCount){await client.query(`UPDATE users SET id=$1 WHERE id=$2`,[desiredUid,existing.rows[0].id]);}else if(existing.rows[0] && existing.rows[0].id!==desiredUid && byUid.rowCount){await client.query(`DELETE FROM users WHERE id=$1`,[existing.rows[0].id]);}await client.query(`INSERT INTO users(id,restaurant_id,email,name,role,password_hash,active) VALUES($1,'nonna-pizzaria',$2,'Fabio Júnior','owner',$3,true) ON CONFLICT(id) DO UPDATE SET restaurant_id='nonna-pizzaria',email=EXCLUDED.email,name=EXCLUDED.name,role='owner',password_hash=EXCLUDED.password_hash,active=true`,[desiredUid,email,hash]);await client.query('COMMIT');res.json({ok:true,tenant:'nonna-pizzaria',userId:desiredUid,role:'owner',imported:true});}catch(e){await client.query('ROLLBACK').catch(()=>{});res.status(500).json({ok:false,error:'owner_import_failed'});}finally{client.release();}});
app.get('/api/admin/migrate/status',migrationGuard,async(_,res)=>{try{const r=await q(`SELECT json_build_object('restaurants',(SELECT count(*)::int FROM restaurants WHERE id='nonna-pizzaria'),'users',(SELECT count(*)::int FROM users WHERE restaurant_id='nonna-pizzaria'),'products',(SELECT count(*)::int FROM products WHERE restaurant_id='nonna-pizzaria'),'orders',(SELECT count(*)::int FROM orders WHERE restaurant_id='nonna-pizzaria')) AS counts`);res.json({ok:true,tenant:'nonna-pizzaria',counts:r.rows[0].counts,lastMigration});}catch{res.status(503).json({ok:false,error:'database_unavailable'});}});
app.use((err, req, res, next) => { if (res.headersSent) return next(err); if (err?.message === 'cors_denied') return res.status(403).json({ error: 'cors_denied' }); console.error('[request]', err?.message || err); res.status(500).json({ error: 'internal_error' }); });
app.use((_,res)=>res.status(404).json({error:'not_found'}));
const port=Number(process.env.PORT)||10000; app.listen(port,()=>console.log(`Nonna API listening on ${port}`));
process.on('SIGTERM',()=>pool.end().finally(()=>process.exit(0)));
