import express from 'express';
import cors from 'cors';
import pg from 'pg';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { migrateFirebase } from './migration-core.mjs';
const { Pool } = pg;
const app = express();
app.disable('x-powered-by');
app.use(cors({ origin: process.env.CORS_ORIGIN ? process.env.CORS_ORIGIN.split(',').map(x=>x.trim()) : true }));
app.use(express.json({ limit: '1mb' }));
const databaseUrl = process.env.DATABASE_URL;
const pool = new Pool({ connectionString: databaseUrl, ssl: databaseUrl ? { rejectUnauthorized:false } : false, max:5, connectionTimeoutMillis:3000, idleTimeoutMillis:10000 });
pool.on('error', e => console.error('[db]', e.message));
const secret = process.env.SESSION_SECRET || process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');
const schema = [
`CREATE TABLE IF NOT EXISTS restaurants(id text PRIMARY KEY,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),email text NOT NULL UNIQUE,name text NOT NULL,role text NOT NULL DEFAULT 'owner',password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),last_access_at timestamptz)`,
`CREATE TABLE IF NOT EXISTS products(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),category text NOT NULL DEFAULT 'Geral',name text NOT NULL,description text,price numeric(12,2) NOT NULL DEFAULT 0,cost numeric(12,2) NOT NULL DEFAULT 0,emoji text,image_url text,active boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS orders(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL DEFAULT 'pending',channel text,customer jsonb NOT NULL DEFAULT '{}',items jsonb NOT NULL DEFAULT '[]',subtotal numeric(12,2) NOT NULL DEFAULT 0,delivery_fee numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL DEFAULT 0,payment jsonb NOT NULL DEFAULT '{}',courier_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS order_events(id bigserial PRIMARY KEY,order_id text NOT NULL REFERENCES orders(id),status text NOT NULL,actor_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS inventory(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),name text NOT NULL,category text,quantity numeric(12,3) NOT NULL DEFAULT 0,min_quantity numeric(12,3) NOT NULL DEFAULT 0,unit text NOT NULL DEFAULT 'un',updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS expenses(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),description text NOT NULL,category text,amount numeric(12,2) NOT NULL CHECK(amount>0),due_date date NOT NULL,paid boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS reservations(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),customer jsonb NOT NULL DEFAULT '{}',table_no text,starts_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'booked',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS cash_registers(id text PRIMARY KEY,restaurant_id text NOT NULL REFERENCES restaurants(id),status text NOT NULL,opened_at timestamptz,closed_at timestamptz,counted numeric(12,2),expected numeric(12,2))`,
`CREATE TABLE IF NOT EXISTS cash_movements(id text PRIMARY KEY,register_id text NOT NULL REFERENCES cash_registers(id),type text NOT NULL,amount numeric(12,2) NOT NULL CHECK(amount>0),description text,actor_id text,created_at timestamptz NOT NULL DEFAULT now())`,`CREATE TABLE IF NOT EXISTS migration_state(key text PRIMARY KEY,completed_at timestamptz NOT NULL DEFAULT now())`];
let schemaReady = false, schemaPromise;
const id = () => crypto.randomUUID();
const json = v => v === undefined ? {} : v;
function hashPassword(password){ const salt=crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`; }
function checkPassword(password, stored){ try { if(typeof stored==='string' && stored.startsWith('$2')) return bcrypt.compareSync(password,stored); const [salt,key]=stored.split(':'); return crypto.timingSafeEqual(crypto.scryptSync(password,salt,64),Buffer.from(key,'hex')); } catch { return false; } }
function token(payload){ const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url'); return `${body}.${crypto.createHmac('sha256',secret).update(body).digest('base64url')}`; }
function readToken(raw){ try { const [body,sig]=raw.split('.'); const good=crypto.createHmac('sha256',secret).update(body).digest('base64url'); if(!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good))) return null; const p=JSON.parse(Buffer.from(body,'base64url')); return p.exp>Date.now()?p:null; } catch { return null; } }
async function ensureSchema(){ if(schemaReady) return; if(!schemaPromise) schemaPromise=(async()=>{ if(!databaseUrl) throw new Error('DATABASE_URL missing'); for(const statement of schema) await pool.query(statement); schemaReady=true; })().catch(e=>{schemaPromise=null; throw e}); return schemaPromise; }
async function q(text, params=[]){ await ensureSchema(); return pool.query({text,values:params}); }
function auth(req,res,next){ const p=readToken((req.headers.authorization||'').replace(/^Bearer\s+/i,'')); if(!p?.uid||!p?.rid) return res.status(401).json({error:'unauthorized'}); req.user=p; next(); }
function bodyFields(body, allowed){ return allowed.map(k=>body[k]); }
const listRoutes = {
 products:['products',['category','name','description','price','cost','emoji','image_url','active']], inventory:['inventory',['name','category','quantity','min_quantity','unit']], expenses:['expenses',['description','category','amount','due_date','paid']], reservations:['reservations',['customer','table_no','starts_at','status']]
};
app.get('/health', async (_,res)=>{ try { await ensureSchema(); res.json({ok:true,service:'nonna-pizzaria-api',database:'connected'}); } catch(e){ res.status(503).json({ok:false,service:'nonna-pizzaria-api',database:'unavailable'}); } });
app.get('/api/config',(req,res)=>res.json({service:'nonna-pizzaria-api',version:'1.0.0',migration:'supported'}));
app.post('/api/auth/register', async(req,res)=>{ const {restaurantName,name,email,password}=req.body||{}; if(!restaurantName||!name||!email||!password||password.length<8) return res.status(400).json({error:'restaurantName,name,email,password(min_8) required'}); const client=await pool.connect(); try { await ensureSchema(); await client.query('BEGIN'); const rid=id(),uid=id(); const r=await client.query('INSERT INTO restaurants(id,name) VALUES($1,$2) RETURNING id,name',[rid,String(restaurantName).trim()]); await client.query('INSERT INTO users(id,restaurant_id,email,name,role,password_hash) VALUES($1,$2,lower($3),$4,$5,$6)',[uid,rid,email.trim(),name.trim(),'owner',hashPassword(password)]); await client.query('COMMIT'); res.status(201).json({token:token({uid,rid,role:'owner'}),restaurant:r.rows[0],user:{id:uid,name,email:email.toLowerCase(),role:'owner'}}); } catch(e){ await client.query('ROLLBACK').catch(()=>{}); res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'email_exists':'registration_failed'}); } finally{client.release();} });
app.post('/api/auth/login', async(req,res)=>{ const {email,password}=req.body||{}; if(!email||!password) return res.status(400).json({error:'email,password required'}); try { const r=await q('SELECT id,restaurant_id,name,email,role,password_hash FROM users WHERE email=lower($1) AND active=true',[email]); const u=r.rows[0]; if(!u||!checkPassword(password,u.password_hash)) return res.status(401).json({error:'invalid_credentials'}); await q('UPDATE users SET last_access_at=now() WHERE id=$1',[u.id]); res.json({token:token({uid:u.id,rid:u.restaurant_id,role:u.role}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}); } catch { res.status(503).json({error:'database_unavailable'}); } });
app.get('/api/me',auth,async(req,res)=>{ try { const r=await q('SELECT u.id,u.name,u.email,u.role,r.id restaurant_id,r.name restaurant_name FROM users u JOIN restaurants r ON r.id=u.restaurant_id WHERE u.id=$1 AND u.restaurant_id=$2',[req.user.uid,req.user.rid]); if(!r.rowCount)return res.status(401).json({error:'unauthorized'}); res.json(r.rows[0]); } catch {res.status(503).json({error:'database_unavailable'});} });
for(const [route,[table,fields]] of Object.entries(listRoutes)){ app.get('/api/'+route,auth,async(req,res)=>{try{const r=await q(`SELECT * FROM ${table} WHERE restaurant_id=$1 ORDER BY ${table === 'products' ? 'updated_at' : 'created_at'} DESC NULLS LAST`,[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}}); app.post('/api/'+route,auth,async(req,res)=>{try{const vals=bodyFields(req.body||{},fields).map((v,i)=>['customer'].includes(fields[i])?json(v):v);const cols=['id','restaurant_id',...fields];const r=await q(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${cols.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,[id(),req.user.rid,...vals]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'invalid_data'})}}); }
app.get('/api/products/public/:restaurantId',async(req,res)=>{try{const r=await q('SELECT id,category,name,description,price,emoji,image_url FROM products WHERE restaurant_id=$1 AND active=true ORDER BY category,name',[req.params.restaurantId]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.get('/api/orders',auth,async(req,res)=>{try{const r=await q('SELECT * FROM orders WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
app.post('/api/orders',auth,async(req,res)=>{const b=req.body||{};if(!Array.isArray(b.items))return res.status(400).json({error:'items_required'});try{const r=await q('INSERT INTO orders(id,restaurant_id,status,channel,customer,items,subtotal,delivery_fee,total,payment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id(),req.user.rid,b.status||'pending',b.channel||'counter',json(b.customer),b.items,Number(b.subtotal)||0,Number(b.delivery_fee)||0,Number(b.total)||0,json(b.payment)]);res.status(201).json(r.rows[0])}catch{res.status(400).json({error:'invalid_order'})}});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{const status=String(req.body?.status||'').trim();if(!status)return res.status(400).json({error:'status_required'});try{const c=await q('UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 RETURNING *',[status,req.params.id,req.user.rid]);if(!c.rowCount)return res.status(404).json({error:'not_found'});await q('INSERT INTO order_events(order_id,status,actor_id) VALUES($1,$2,$3)',[req.params.id,status,req.user.uid]);res.json(c.rows[0])}catch{res.status(400).json({error:'invalid_status'})}});
app.get('/api/orders/:id/events',auth,async(req,res)=>{try{const r=await q('SELECT e.* FROM order_events e JOIN orders o ON o.id=e.order_id WHERE e.order_id=$1 AND o.restaurant_id=$2 ORDER BY e.created_at',[req.params.id,req.user.rid]);res.json(r.rows)}catch{res.status(503).json({error:'database_unavailable'})}});
const migrationAuthorized=req=>{const expected=process.env.MIGRATION_TOKEN;const supplied=req.get('x-migration-token')||(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!expected||!supplied||expected.length!==supplied.length)return false;return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied));};
const migrationGuard=(req,res,next)=>migrationAuthorized(req)?next():res.status(404).json({error:'not_found'});
let lastMigration=null;
app.post('/api/admin/migrate',migrationGuard,async(req,res)=>{try{const result=await migrateFirebase(req.body,pool);lastMigration={...result,completedAt:new Date().toISOString()};res.json(lastMigration);}catch(e){console.error('[migration]',e.message);res.status(500).json({ok:false,error:'migration_failed'});}});
app.post('/api/admin/migrate/owner',migrationGuard,async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const password=typeof req.body?.password==='string'?req.body.password:'';if(email!=='fabio08dejesusjunior@gmail.com'||password.length<8)return res.status(400).json({ok:false,error:'invalid_owner_payload'});const client=await pool.connect();try{await ensureSchema();await client.query('BEGIN');const claimed=await client.query(`INSERT INTO migration_state(key) VALUES('nonna-owner-credential-v6') ON CONFLICT(key) DO NOTHING RETURNING key`);if(!claimed.rowCount){await client.query('ROLLBACK');return res.status(409).json({ok:false,error:'owner_already_imported'});}const hash=await bcrypt.hash(password,12);const desiredUid='HaUqvQd6muYH3zUNUpwBOhD29Bf1';const existing=await client.query(`SELECT id FROM users WHERE restaurant_id=$1 AND lower(email)=lower($2) LIMIT 1`,['nonna-pizzaria',email]);const byUid=await client.query(`SELECT id FROM users WHERE id=$1`,[desiredUid]);if(existing.rows[0] && existing.rows[0].id!==desiredUid && !byUid.rowCount){await client.query(`UPDATE users SET id=$1 WHERE id=$2`,[desiredUid,existing.rows[0].id]);}else if(existing.rows[0] && existing.rows[0].id!==desiredUid && byUid.rowCount){await client.query(`DELETE FROM users WHERE id=$1`,[existing.rows[0].id]);}await client.query(`INSERT INTO users(id,restaurant_id,email,name,role,password_hash,active) VALUES($1,'nonna-pizzaria',$2,'Fabio Júnior','owner',$3,true) ON CONFLICT(id) DO UPDATE SET restaurant_id='nonna-pizzaria',email=EXCLUDED.email,name=EXCLUDED.name,role='owner',password_hash=EXCLUDED.password_hash,active=true`,[desiredUid,email,hash]);await client.query('COMMIT');res.json({ok:true,tenant:'nonna-pizzaria',userId:desiredUid,role:'owner',imported:true});}catch(e){await client.query('ROLLBACK').catch(()=>{});res.status(500).json({ok:false,error:'owner_import_failed'});}finally{client.release();}});
app.get('/api/admin/migrate/status',migrationGuard,async(_,res)=>{try{const r=await q(`SELECT json_build_object('restaurants',(SELECT count(*)::int FROM restaurants WHERE id='nonna-pizzaria'),'users',(SELECT count(*)::int FROM users WHERE restaurant_id='nonna-pizzaria'),'products',(SELECT count(*)::int FROM products WHERE restaurant_id='nonna-pizzaria'),'orders',(SELECT count(*)::int FROM orders WHERE restaurant_id='nonna-pizzaria')) AS counts`);res.json({ok:true,tenant:'nonna-pizzaria',counts:r.rows[0].counts,lastMigration});}catch{res.status(503).json({ok:false,error:'database_unavailable'});}});
app.use((_,res)=>res.status(404).json({error:'not_found'}));
const port=Number(process.env.PORT)||10000; app.listen(port,()=>console.log(`Nonna API listening on ${port}`));
process.on('SIGTERM',()=>pool.end().finally(()=>process.exit(0)));
